resources:
  containers:
  - container: wpilib2020
    image: wpilib/roborio-cross-ubuntu:2020-18.04
  - container: raspbian
    image:  wpilib/raspbian-cross-ubuntu:10-18.04
  - container: bionic
    image: wpilib/aarch64-cross-ubuntu:bionic-18.04


stages:
- stage: Build
  jobs:
  - job: Linux_Arm_Pi
    pool:
      vmImage: 'Ubuntu 16.04'

    container: raspbian

    steps:
      - checkout: self  # self represents the repo where the initial Pipelines YAML file was found
        submodules: true
      - script: |
          sudo apt-get update && sudo apt-get install ant -y && sudo rm -rf /var/lib/apt/lists/*
        displayName: 'Install Ant'
      - task: Gradle@2
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          publishJUnitResults: false
          testResultsFiles: '**/TEST-*.xml'
          tasks: 'build'
          options: '-Pplatform=linux-raspbian -PjenkinsBuild'

      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'Raspbian'
          targetPath: 'gradleDir/outputs'

  - job: Linux_Bionic
    pool:
      vmImage: 'Ubuntu 16.04'

    container: bionic

    steps:
      - checkout: self  # self represents the repo where the initial Pipelines YAML file was found
        submodules: true
      - script: |
          sudo apt-get update && sudo apt-get install ant -y && sudo rm -rf /var/lib/apt/lists/*
        displayName: 'Install Ant'
      - task: Gradle@2
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          publishJUnitResults: false
          testResultsFiles: '**/TEST-*.xml'
          tasks: 'build'
          options: '-Pplatform=linux-aarch64bionic -PjenkinsBuild'

      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'Bionic'
          targetPath: 'gradleDir/outputs'

  - job: Linux_Arm
    pool:
      vmImage: 'Ubuntu 16.04'

    container: wpilib2020

    timeoutInMinutes: 0

    steps:
      - checkout: self  # self represents the repo where the initial Pipelines YAML file was found
        submodules: true
      - script: |
          sudo apt-get update && sudo apt-get install ant -y && sudo rm -rf /var/lib/apt/lists/*
        displayName: 'Install Ant'
      - task: Gradle@2
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          publishJUnitResults: false
          testResultsFiles: '**/TEST-*.xml'
          tasks: 'build'
          options: '-Pplatform=linux-athena -PjenkinsBuild'

      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'Athena'
          targetPath: 'gradleDir/outputs'


  - job: Linux
    pool:
      vmImage: 'Ubuntu 16.04'

    container: wpilib2020

    timeoutInMinutes: 0

    steps:
      - checkout: self  # self represents the repo where the initial Pipelines YAML file was found
        submodules: true
      - script: |
          sudo apt-get update && sudo apt-get install ant -y && sudo rm -rf /var/lib/apt/lists/*
        displayName: 'Install Ant'
      - task: Gradle@2
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          options: '-PjenkinsBuild'
          publishJUnitResults: false
          testResultsFiles: '**/TEST-*.xml'
          tasks: 'build'

      - script: |
          ls -la
          ls -la build/

      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'Linux'
          targetPath: 'gradleDir/outputs'

  - job: Windows_64_Bit_Release
    pool:
      vmImage: 'windows-2019'

    timeoutInMinutes: 0

    steps:
      - checkout: self  # self represents the repo where the initial Pipelines YAML file was found
        submodules: true
      - powershell: |
          mkdir build
          $ProgressPreference = 'SilentlyContinue'
          wget "https://download.java.net/java/ga/jdk11/openjdk-11_windows-x64_bin.zip" -O "build\jdk.zip"
        displayName: 'Download JDK'
      - task: JavaToolInstaller@0
        inputs:
          jdkSourceOption: localDirectory
          jdkFile: 'build/jdk.zip'
          jdkDestinationDirectory: 'build/jdkinst'
          jdkArchitectureOption: x64
      - script: |
          @call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"
          set PATH=%PATH%;%ANT_HOME%\bin
          gradlew build -PjenkinsBuild -PskipDebug
        displayName: 'Gradle Build'

      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'Win64Release'
          targetPath: 'gradleDir/outputs'

  - job: Windows_32_Bit_Release
    pool:
      vmImage: 'windows-2019'

    timeoutInMinutes: 0

    steps:
      - checkout: self  # self represents the repo where the initial Pipelines YAML file was found
        submodules: true
      - powershell: |
          mkdir build
          $ProgressPreference = 'SilentlyContinue'
          wget "https://github.com/wpilibsuite/frc-openjdk-windows/releases/download/v11.0.0u28-1/jdk-x86-11.0.0u28-1.zip" -O "build\jdk.zip"
        displayName: 'Download JDK'
      - task: JavaToolInstaller@0
        inputs:
          jdkSourceOption: localDirectory
          jdkFile: 'build/jdk.zip'
          jdkDestinationDirectory: 'build/jdkinst'
          jdkArchitectureOption: x86
      - script: |
          @call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Auxiliary\\Build\\vcvars32.bat"
          set PATH=%PATH%;%ANT_HOME%\bin
          gradlew build -PjenkinsBuild -PskipDebug
        displayName: 'Gradle Build'

      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'Win32Release'
          targetPath: 'gradleDir/outputs'

  - job: Windows_64_Bit
    pool:
      vmImage: 'windows-2019'

    timeoutInMinutes: 0

    steps:
      - checkout: self  # self represents the repo where the initial Pipelines YAML file was found
        submodules: true
      - powershell: |
          mkdir build
          $ProgressPreference = 'SilentlyContinue'
          wget "https://download.java.net/java/ga/jdk11/openjdk-11_windows-x64_bin.zip" -O "build\jdk.zip"
        displayName: 'Download JDK'
      - task: JavaToolInstaller@0
        inputs:
          jdkSourceOption: localDirectory
          jdkFile: 'build/jdk.zip'
          jdkDestinationDirectory: 'build/jdkinst'
          jdkArchitectureOption: x64
      - script: |
          @call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"
          set PATH=%PATH%;%ANT_HOME%\bin
          gradlew build -PjenkinsBuild -PskipRelease -PskipSources
        displayName: 'Gradle Build'

      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'Win64'
          targetPath: 'gradleDir/outputs'

  - job: Windows_32_Bit
    pool:
      vmImage: 'windows-2019'

    timeoutInMinutes: 0

    steps:
      - checkout: self  # self represents the repo where the initial Pipelines YAML file was found
        submodules: true
      - powershell: |
          mkdir build
          $ProgressPreference = 'SilentlyContinue'
          wget "https://github.com/wpilibsuite/frc-openjdk-windows/releases/download/v11.0.0u28-1/jdk-x86-11.0.0u28-1.zip" -O "build\jdk.zip"
        displayName: 'Download JDK'
      - task: JavaToolInstaller@0
        inputs:
          jdkSourceOption: localDirectory
          jdkFile: 'build/jdk.zip'
          jdkDestinationDirectory: 'build/jdkinst'
          jdkArchitectureOption: x86
      - script: |
          @call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Auxiliary\\Build\\vcvars32.bat"
          set PATH=%PATH%;%ANT_HOME%\bin
          gradlew build -PjenkinsBuild -PskipRelease -PskipSources
        displayName: 'Gradle Build'

      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'Win32'
          targetPath: 'gradleDir/outputs'

  - job: Mac
    pool:
      vmImage: 'macOS-10.14'

    timeoutInMinutes: 0

    steps:
      - checkout: self  # self represents the repo where the initial Pipelines YAML file was found
        submodules: true
      - script: |
          mkdir build
          export JAVA_HOME=`/usr/libexec/java_home -v 11`
          brew install ant binutils
        displayName: 'Setup JDK Ant and Binutils'
      - task: Gradle@2
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          jdkVersionOption: '1.11'
          publishJUnitResults: false
          testResultsFiles: '**/TEST-*.xml'
          options: '-PjenkinsBuild'
          tasks: 'build'

      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'Mac'
          targetPath: 'gradleDir/outputs'

- stage: Combine
  jobs:
  - job: CombineJob
    pool:
      vmImage: 'macOS-10.14'

    steps:
    - checkout: none
    - script: |
        git clone https://github.com/wpilibsuite/build-tools
      displayName: 'Clone Combiner'
    - task: DownloadPipelineArtifact@0
      inputs:
        artifactName: 'Mac'
        targetPath: 'build-tools/combiner/products/build/allOutputs'
    - task: DownloadPipelineArtifact@0
      inputs:
        artifactName: 'Win32'
        targetPath: 'build-tools/combiner/products/build/allOutputs'
    - task: DownloadPipelineArtifact@0
      inputs:
        artifactName: 'Win64'
        targetPath: 'build-tools/combiner/products/build/allOutputs'
    - task: DownloadPipelineArtifact@0
      inputs:
        artifactName: 'Win32Release'
        targetPath: 'build-tools/combiner/products/build/allOutputs'
    - task: DownloadPipelineArtifact@0
      inputs:
        artifactName: 'Win64Release'
        targetPath: 'build-tools/combiner/products/build/allOutputs'
    - task: DownloadPipelineArtifact@0
      inputs:
        artifactName: 'Linux'
        targetPath: 'build-tools/combiner/products/build/allOutputs'
    - task: DownloadPipelineArtifact@0
      inputs:
        artifactName: 'Bionic'
        targetPath: 'build-tools/combiner/products/build/allOutputs'
    - task: DownloadPipelineArtifact@0
      inputs:
        artifactName: 'Raspbian'
        targetPath: 'build-tools/combiner/products/build/allOutputs'
    - task: DownloadPipelineArtifact@0
      inputs:
        artifactName: 'Athena'
        targetPath: 'build-tools/combiner/products/build/allOutputs'
    - task: Gradle@2
      inputs:
        workingDirectory: 'build-tools/combiner'
        gradleWrapperFile: 'build-tools/combiner/gradlew'
        gradleOptions: '-Xmx3072m'
        tasks: 'publish '
        options: '-Pthirdparty'
    - script: |
        echo "##vso[task.setvariable variable=UserHome]$HOME"
      displayName: 'Set Home Variable'
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'Maven'
        targetPath: $(UserHome)/releases
